version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      nestjs:
        patterns: ['@nestjs/*']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: node
        update-types: [version-update:semver-major]
  - package-ecosystem: npm
    directory: /mobile
    schedule:
      interval: weekly
    groups:
      expo-sdk:
        patterns: ['expo*', '@expo/*', 'react*', '@types/react']
